version: '2.1'
services:
  node-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    networks:
      - default
    volumes:
      - .:/usr/src/app/:rw
      - ./node_modules:/usr/src/app/node_modules
    command: npm run server
volumes:
  vendor: