version: '2.1'
services:
  node-server:
    build: .
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - .:/usr/src/app/:rw
      - vendor:/usr/src/app/node_modules
    command: "${COMMAND-npm run serve}"
volumes:
  vendor: